sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

app_newsletter_subscribe :
    path: /{_locale}/newsletter
    methods: [GET, POST]
    controller: App\Controller\Shop\NewsletterController::subscribe

app_shop_recipe_index :
    path: /{_locale}/recipes
    methods: [GET, POST]
    controller: App\Controller\Shop\RecipeController::index

app_shop_recipe_show :
    path: /{_locale}/recipe-presentation/{title}
    methods: [GET, POST]
    controller: App\Controller\Shop\RecipeController::show

app.recipe:
    resource: |
        alias: app.recipe
        section: admin
        path: /recipe
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_recipe
        vars:
            all:
                subheader: Recipe
                templates:
                    form: "@SyliusAdmin\\Recipe\\_form.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin